# note that the following 3 directory config settings end with a '/' and represent explicit routes from asset_builder.rb to the resource
js-output-dir: '../priv/static/js/'
css-output-dir: '../priv/static/css/'
custom-js-input-dir: '../assets/js/'
custom-styles-input-dir: '../assets/styles/'

js-files-to-compile:
  # required components
  - global.js
  - cash.js
  - component.js
  - anime.min.js
  # elements used in template
  - sidenav.js
  - modal.js
  # elements on album page
  - buttons.js
  - cards.js
  - tabs.js
  - chips.js # only needed for chips form
  - toasts.js
  - select.js
  - dropdown.js
